behaviors:
  AgentControl:
    trainer_type: ppo
    hyperparameters: 
      batch_size: 512
      buffer_size: 2048
      learning_rate: 0.0001
      beta: 0.03
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000
